version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
    - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ../:/var/www/html

  php:
    container_name: php-fpm
    build:
      context: ./php
    volumes:
      - ../:/var/www/html

  mysql:
    container_name: mysql
    image: mysql:8.0
    volumes:
      - mysql/:/var/lib/mysql
    environment:
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      MYSQL_ROOT_PASSWORD: docker
